# Generated by Django 3.2.6 on 2021-08-18 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210818_0114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='subject',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='number',
        ),
    ]
